<<<<<<< HEAD
name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install -g surge

=======
name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install -g surge

>>>>>>> 5fcb62ef683f4d0a8adcb2624272f8c5e5be537f
      - run: surge ./ TU-NOMBRE.surge.sh --token ${{ secrets.SURGE_TOKEN }}